services:
  usersvc:
    build: 
      context: .
      dockerfile: Dockerfile
      network: host
    command: [ "hypercorn", "src.user:app", "--bind", "0.0.0.0:5050" ]
    ports:
      - "5050:5050"
    volumes:
      - ./data_users:/app/data
      - ./shared_data:/app/shared_data
    environment:
      - PORT=5050
    restart: unless-stopped
  
  apisvc:
    build: 
      context: .
      dockerfile: Dockerfile
      network: host
    command: [ "hypercorn", "src.api:app", "--bind", "0.0.0.0:5051" ]
    ports:
      - "5051:5051" 
    volumes:
      - ./data_users:/app/data
      - ./shared_data:/app/shared_data
    environment:
      - PORT=5051
    depends_on:
      - usersvc
    restart: unless-stopped
  
  dbsvc:
    image: postgres:16
    container_name: dbsvc
    environment:
      POSTGRES_USER: alumnodb
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: si1
    ports:
      - "5432:5432"
    volumes:
      - ./data_files:/var/lib/postgresql/data #cambiar
    restart: unless-stopped